name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      run: |
        echo "$SSH_PRIVATE_KEY" > key
        chmod 600 key
        eval "$(ssh-agent -s)"
        ssh-add key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key ubuntu@13.53.123.251 "cd /var/www/html/ec2-practice && git pull origin main"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
